Fixed axis method configuration error
ninetydays/kross-SDK pull request #244
Opened 2024-04-19 00:09 UTC by Rzzvaan-Muhammad

Fixed POST, PUT, PATCH method configuration error.

2024-04-19 04:22 UTC, Jscripter-pk approved these changes

2024-04-19 04:46 UTC, Danue1 requested changes

2024-04-19 04:46 UTC, Danue1 commented on src/kross-client/base.ts
> +    return this.instance.put<T>(url, data, config);
For next reviewers, we can refer to https://axios-http.com/docs/api_intro.

2024-04-19 04:46 UTC, Danue1 commented on src/kross-client/base.ts
>    }
The `R` has wrong type.
Since the `T` is for data, and the `R` is for json of response.body.
I think we can change it in one of two ways.

```tsx
  patch<D = unknown, T = unknown, R = AxiosResponse<T>>(
    url: string,
    data?: D,
    config?: AxiosRequestConfig
  ): Promise<R> {
    return this.instance.patch(url, data, config);
  }
```

```tsx
  patch<T = unknown, R = AxiosResponse<T>>(
    url: string,
    data?: any,
    config?: AxiosRequestConfig
  ): Promise<R> {
    return this.instance.patch(url, data, config);
  }
```

2024-04-19 05:28 UTC, Danue1 approved these changes
LGTM

2024-04-22 00:34 UTC, JonghunYu approved these changes

2024-04-22 00:34 UTC, merged