chore get new loans list
ninetydays/kross-SDK pull request #30
Opened 2023-01-30 06:22 UTC by aziyatali

Removed some redundant codes and added newProduct list based joining it with investments whether current user has invested or not!

2023-01-30 15:44 UTC, Jscripter-pk commented
@aziyatali there is no need of optional user_id to be passed it can be checked via parsing jwt token and checking if token is not expired then use the user_id from there

2023-01-30 15:46 UTC, aziyatali commented
@Jscripter-pk So, just adding parserToken function would solve extra attribute right?

2023-01-30 16:25 UTC, aziyatali commented
@Jscripter-pk Islam, added token parser in utils and did as you instructed. Please kindly review

2023-01-30 16:34 UTC, Jscripter-pk requested changes
@aziyatali please don't use the naming directly from newloan. Please give some better names

2023-01-30 16:51 UTC, aziyatali commented
@Jscripter-pk Please take a look!

2023-01-30 17:45 UTC, Jscripter-pk requested changes
Few things are missing 
also check for token expiration
and await for getting parsed token so that it don't lead to inconsistency

2023-01-31 05:29 UTC, aziyatali commented
@Jscripter-pk Please review this PR, refactored some tests & skipped post requests since we do not have valid parameters. Let's test them while integrating once we finish loans & loans detail

2023-01-31 05:35 UTC, Jscripter-pk requested changes
@aziyatali 
1. Instead of skipping test mock them.
 2. I see you remove params from even get functions please make sure that atleast pass some params that make sure that they work as expected.

2023-01-31 05:40 UTC, aziyatali commented
@Jscripter-pk Let's create new PR for mocking although we didn't really have tests for post requests from the beginning. Since this PR is for loans joining with investments so we can get started with integration asap

2023-01-31 05:44 UTC, Jscripter-pk commented
@aziyatali when you make a PR related to one specific thing make sure you only touch that part as It messes things up for reviews. Let me first just release a beta version of it and see if it works

2023-01-31 05:46 UTC, aziyatali commented
Got it!

2023-01-31 05:58 UTC, Jscripter-pk requested changes
@aziyatali please add back infinite query implementation back that I added.

2023-01-31 06:00 UTC, Jscripter-pk commented on src/kross-client/loans.ts
> +          ...item,
and moreover I asked you to not use the names from newloan 
I would prefer isUserInvest over is_user_invest

2023-01-31 06:01 UTC, aziyatali commented
> @aziyatali please add back infinite query implementation back that I added.

@Jscripter-pk I didn't touch to LoanData you implemented, what do you mean?

2023-01-31 06:05 UTC, aziyatali commented on src/kross-client/loans.ts
> +          ...item,
Those are the table attributes, checked production table and followed the naming convention there. 

<img width="948" alt="Screen Shot 2023-01-31 at 3 05 34 PM" src="https://user-images.githubusercontent.com/46732700/215679604-a6e88af8-2e78-4e06-8d39-fcc1510f938d.png">

2023-01-31 06:07 UTC, Jscripter-pk commented
@aziyatali I checked what you did in a seperate function that should be done in loans function.
I think at one place JH have told to go with generic one. As Loans screen is using loanData() function so please make it through loanData instead of creating a new function.

2023-01-31 06:22 UTC, aziyatali commented
> @aziyatali I checked what you did in a seperate function that should be done in loans function. I think at one place JH have told to go with generic one. As Loans screen is using loanData() function so please make it through loanData instead of creating a new function.

loanData is a hook function which gets loans. They are same.
I know that we won’t be using loanData hook you implemented instead use loan hook I created for loans & loan details page as per our yerderday's discussion.

2023-01-31 07:05 UTC, Jscripter-pk commented on src/kross-client/loans.ts
> +                    ...item,
@aziyatali overall now it looks fine just change this part as we are passing this from sdk but not from db directly so I think we can use isUserIvest casing here

2023-01-31 07:07 UTC, aziyatali commented on src/kross-client/loans.ts
> +                    ...item,
Got it!

2023-01-31 07:34 UTC, Jscripter-pk approved these changes

2023-01-31 07:40 UTC, merged