Total assets
ninetydays/kross-SDK pull request #40
Opened 2023-02-06 02:34 UTC by aziyatali

Get total assets for each day!

2023-02-06 04:25 UTC, Jscripter-pk commented on src/kross-client/user.ts
> +            for (const noteLog of noteLogsArray) {
@aziyatali nested for loop should be avoided here.

2023-02-06 04:25 UTC, Jscripter-pk commented on src/kross-client/user.ts
> +                break;
Why we used break here?

2023-02-06 04:34 UTC, aziyatali commented on src/kross-client/user.ts
> +                break;
skips the noteLog loop from and goes to next accountLog index

2023-02-06 04:38 UTC, aziyatali commented on src/kross-client/user.ts
> +            for (const noteLog of noteLogsArray) {
Agreed, let me fix it.

2023-02-06 04:42 UTC, Jscripter-pk commented on src/kross-client/user.ts
> +                break;
instead of doing this way use JS built in functions like **find**

2023-02-06 06:55 UTC, Jscripter-pk requested changes
@aziyatali Can you please cross check this with reference to frontend as from frontend we are showing based on selection filter so it will be better to search based on filter like 1month, 3 months, 6 months graph as shown in the design

2023-02-06 06:58 UTC, aziyatali commented
> @aziyatali Can you please cross check this with reference to frontend as from frontend we are showing based on selection filter so it will be better to search based on filter like 1month, 3 months, 6 months graph as shown in the design

Makes sense rather getting whole data.

2023-02-06 07:03 UTC, aziyatali commented
> @aziyatali Can you please cross check this with reference to frontend as from frontend we are showing based on selection filter so it will be better to search based on filter like 1month, 3 months, 6 months graph as shown in the design <img alt="Screenshot 2023-02-06 at 11 59 22 AM" width="581" src="https://user-images.githubusercontent.com/36015615/216904177-0c5dfd18-d066-4b99-8040-6b9c45bcfda5.png"> also check for the percentage and attach it based on data from sdk

got it. Probably, (currentTotalAssets/xMonthsAgoTotalAssets) * 100

2023-02-06 08:24 UTC, aziyatali commented
@Jscripter-pk  Now we can filter the date by inputing number, totalAssets(1) for 1 months etc. If data doesn't exist for that period then it return available data and growthRate

2023-02-06 08:32 UTC, Jscripter-pk requested changes

2023-02-06 08:32 UTC, Jscripter-pk commented on src/kross-client/user.ts
> +          const daysInMonth = 30 * number;
@aziyatali this is not how we will calculate check the function below and return result based on date between start and end date 

```
 getStartAndEndDate = (
  repaymentFilter: string,
): [string, string] => {
  const month = repaymentFilter ? parseInt(repaymentFilter[0], 10) : 6;
  const today = new Date();
  const startDate = addMonths(today, -month);
  const endDate = addMonths(startDate, month);
  return [format(startDate, 'yyyy-MM-dd'), format(endDate, 'yyyy-MM-dd')];
};
```

2023-02-06 08:32 UTC, Jscripter-pk commented on src/kross-client/user.ts
> +          const daysInMonth = 30 * number;
And also check by releasing version of it and test this by integrating in screen.

2023-02-06 08:38 UTC, aziyatali commented on src/kross-client/user.ts
> +          const daysInMonth = 30 * number;
Got it, could have considered that case

2023-02-07 04:37 UTC, aziyatali commented
@Jscripter-pk Please review and merge if you think everything is okay. Tested with app and working properly. As you requested changed the argument range of dates.

2023-02-07 05:00 UTC, Jscripter-pk reviewed
@aziyatali push the integrations changes in this [PR](https://github.com/ninetydays/kross-investor-mobile-app/pull/76) with changes you tested

2023-02-08 06:58 UTC, merged