chore: implement verification functions
ninetydays/kross-SDK pull request #49
Opened 2023-02-09 01:23 UTC by aziyatali

2023-02-09 13:32 UTC, aziyatali commented
@Jscripter-pk  Please take a look to this. I was not able to fix this.
Basically, when I get the image and pass it as form, getting an error. 

Please let me know if you find anything useful, otherwise I will try to look for tomorrow!

<img width="1042" alt="Screen Shot 2023-02-09 at 10 27 51 PM" src="https://user-images.githubusercontent.com/46732700/217826417-86761104-a66b-4b29-a285-bc7b8c8cefc3.png">

2023-02-09 13:47 UTC, Jscripter-pk requested changes
@aziyatali It would be better to have meeting with @MuhammadBilal789 about how he is making endpoint accept id card photo and the other thing that I would suggest here is having a seperate module for Verifications related endpoint so that we have to look specifically in one module when working with verifications

2023-02-09 14:02 UTC, aziyatali commented
@MuhammadBilal789 Would you please review the verifications/idcare/ocr and let me know if anything is wrong?

2023-03-06 11:34 UTC, Jscripter-pk commented
@aziyatali I added and fixed few things you just have to add you id card with idCard.jpeg name in test directory.
After Bilal provide you with further clarifications why 400/500 error is happening you can make changes accordingly then

2023-03-08 01:07 UTC, aziyatali commented
@Jscripter-pk  Here is the working code. Also fixed the config header.
From app side, able to hit the server. Currently having issue: "please upload png, or jpg file, there are some issues with react-native-image-picker'. I think we should move to expo-image-picker since react-native-imgage-picker has MIME type issues which is buggy when we send the image over the network

2023-03-08 04:19 UTC, Jscripter-pk reviewed
Test it on app side by releasing with these changes and see if it works fine with app

2023-03-08 04:20 UTC, aziyatali commented
> Test it on app side by releasing with these changes and see if it works fine with app

Tested and it is working fine. Please check the latest changes on app side.

2023-03-08 04:49 UTC, Jscripter-pk commented
@aziyatali getting this error with the changes you make in app and let me tell you few things which you might be mis confusing with
```"message": "파일형식이 올바르지 않습니다. jpg, png파일을 이용해주세요.", "success": false}
```
This type error is coming because you are passing object without any image actually in formData image part 
```const formattedFile = {
      lastModified: new Date().getTime(),
      lastModifiedDate: new Date(),
      name: file?.fileName,
      size: file?.fileSize,
      type: 'image/jpg',
      webkitRelativePath: '',
    };
    ```
   The above is just a javascript object not an image/file which is supposed to be send to the endpoint that's why it give type error not because of mime type. I have told you it is not a mime type issue I tested with normal axios even with rn-image-picker library we are using. Just check the pattern thing and try to compare the data sent to the endpoint in case of bilal RN sent.

2023-03-08 04:54 UTC, aziyatali commented
> @aziyatali getting this error with the changes you make in app and let me tell you few things which you might be mis confusing with
> 
> This type error is coming because you are passing object without any image actually in formData image part
> 
> ```
>       lastModified: new Date().getTime(),
>       lastModifiedDate: new Date(),
>       name: file?.fileName,
>       size: file?.fileSize,
>       type: 'image/jpg',
>       webkitRelativePath: '',
>     };
> ```
> 
> The above is just a javascript object not an image/file which is supposed to be send to the endpoint that's why it give type error not because of mime type. I have told you it is not a mime type issue I tested with normal axios even with rn-image-picker library we are using. Just check the pattern thing and try to compare the data sent to the endpoint in case of bilal RN sent.

[ const formattedFile = {
      lastModified: new Date().getTime(),
      lastModifiedDate: new Date(),
      uri: file?.uri,
      name: file?.fileName,
      size: file?.fileSize,
      type: file?.type,
      webkitRelativePath: ""
    }](url)
    
    Working like a magic!
    Please add url and pass actual uri and it will work!

2023-03-08 05:07 UTC, aziyatali commented
@Jscripter-pk Please review changes that I moved from base to verifications and merge if everything is ok

2023-03-08 05:55 UTC, Jscripter-pk reviewed
Please remove the console.logs from the code and fixed the comment I leave

2023-03-08 05:55 UTC, Jscripter-pk commented on src/types/kross-client/index.ts
> +  isBusiness?: boolean;
<img width="1046" alt="Screenshot 2023-03-08 at 10 49 52 AM" src="https://user-images.githubusercontent.com/36015615/223630411-37f6b1f5-0711-4044-9e5d-9cadeac74cc5.png">

2023-03-08 06:55 UTC, aziyatali commented on src/types/kross-client/index.ts
> +  isBusiness?: boolean;
Those are the optional values which were incorrectly put in the docs. Ijaz confirmed!

2023-03-08 06:58 UTC, Jscripter-pk requested changes
isBorrower and isBusiness both are required that's why I shared a screenshot with you so that you can see it clearly

2023-03-08 07:03 UTC, aziyatali commented
> isBorrower and isBusiness both are required that's why I shared a screenshot with you so that you can see it clearly

Ijaz told those are optional params. He will update the docs.

2023-03-08 07:13 UTC, merged