chore: api call env set-up
ninetydays/kross-SDK pull request #6
Opened 2022-12-13 09:11 UTC by aziyatali

Tried to set initial api call, there are lots of things I do not know. Just sharing progress. To be continued tomorrow!
Also, need to restructure them so we can get function lists with single or a few exports!

2022-12-16 09:01 UTC, aziyatali commented
@Jscripter-pk , would you please review the code structure, inheritance class and give some feedback please?
Available endpoints in olive has been implemented so far. 
After, I will ask @JonghunYu regarding structure whether we are moving all the endpoint calls here so we can use them for new-loan and other mobile apps.

2022-12-16 09:41 UTC, Jscripter-pk reviewed
@aziyatali I think QueryType is going to be dynamic. As We will be passing whatever will be required to pass.
And As I can see you have added jest config. I would suggest basic test for the functions you wrote. Atleast the test that give some confidence that what you are doing is working

2022-12-22 08:07 UTC, aziyatali commented
@JonghunYu님, would you please review the src folder where functions for all the endpoints were implemented. Also, handled the case client case. 
Test cases to be implemented(in progress)

2022-12-22 08:19 UTC, JonghunYu requested changes
@aziyatali 

@Jscripter-pk Please review this PR too

2022-12-22 08:19 UTC, JonghunYu commented on package.json
> +    "prettier": "prettier --write -c .prettierrc.json"
rename this `format` as it cause conflict with running prettier itself

2022-12-22 08:19 UTC, JonghunYu commented on package.json
> +    "prettier": "prettier --write -c .prettierrc.json"
and I think you don't need to specify config file with `-c .prettierrc.json` as it's a default path

2022-12-22 08:19 UTC, JonghunYu commented on __test__/auth.test.ts
> +      return request(app.getHttpServer())
this won't work

2022-12-22 08:19 UTC, JonghunYu commented on package.json
> +    "@nestjs/common": "^9.2.1",
do you have any reason to install this?

2022-12-22 08:19 UTC, JonghunYu commented on src/api/loans.tsx
> +export class Accounts extends KrossClient {
Loans?

2022-12-22 08:19 UTC, JonghunYu commented on src/kross-client.ts
> +            })
```ts
config.headers = {
  ...config.headers,
  'client-authorization': hmacToken,
  'X-Date': xDate,
};

if (this.authToken) {
  config.headers = {
    ...config.headers,
    authorization: `Bearer ${this.authToken}`,
  };
}
```

2022-12-22 08:19 UTC, JonghunYu commented on src/types/index.ts
> +}
You shouldn't add specific fields only used in some endpoints but define them as a separate type

2022-12-22 08:34 UTC, aziyatali commented on package.json
> +    "@nestjs/common": "^9.2.1",
I was planning to use them for mock testing purpose for invalid data of predefined data(to generate invalid credentials).

2022-12-22 08:35 UTC, aziyatali commented on __test__/auth.test.ts
> +      return request(app.getHttpServer())
Yes, it was the test case in the beginning which to be updated soon

2022-12-22 08:36 UTC, aziyatali commented on src/api/loans.tsx
> +export class Accounts extends KrossClient {
Gotcha!

2022-12-22 08:38 UTC, aziyatali commented on src/kross-client.ts
> +import { KrossClientOptions } from './types/index'
currently outtdated

2022-12-22 09:00 UTC, Jscripter-pk commented on src/kross-client.ts
> +    this.client.interceptors.response.use(
@aziyatali What do you think of creating a function with a proper name that defines the purpose of this piece of code

2022-12-29 05:01 UTC, aziyatali commented on src/api/investments.tsx
> +    this.method = 'get'
It used method for hashing the hmac. What do you suggest?

2022-12-29 05:02 UTC, aziyatali commented on src/kross-client.ts
> +    this.client.interceptors.response.use(
Islam, I think leaving them as they are better maybe, it handles intercepts response

2023-01-03 05:19 UTC, aziyatali commented
@JonghunYu @Jscripter-pk , Would please review it? 
Currently implemented mock testing just for login and users.

2023-01-03 06:10 UTC, Jscripter-pk commented
@aziyatali mocking is not required here use mock responses in case of kftc / third party services

2023-01-09 01:34 UTC, JonghunYu approved these changes

2023-01-09 01:34 UTC, merged