chore: have same response format for infiniteQuery
ninetydays/kross-SDK pull request #63
Opened 2023-02-16 04:19 UTC by aziyatali

@Jscripter-pk Made other infiniteQueries have same format with Loans we have. 
response -> response.pages, response.pageParam -> response.pages.data
Previously data had another response status and data. It is confusing to parse.

2023-02-16 10:20 UTC, Jscripter-pk requested changes

2023-02-16 10:20 UTC, Jscripter-pk commented on src/kross-client/inquiry.ts
> +            const inquiriesDataArray = inquiriesData?.data
@aziyatali don't you think that this piece of code becomes so complex to read even.
Please try to simplify this a bit.

2023-02-17 04:47 UTC, Jscripter-pk requested changes

2023-02-17 04:47 UTC, Jscripter-pk commented on src/kross-client/inquiry.ts
> +            const inquiriesDataArray = Array.isArray(inquiriesData?.data)
Why isArray when we already know that we are going to get empty array in case there is no data and ?. operator do the rest for us. just remove it

2023-02-17 04:55 UTC, aziyatali commented on src/kross-client/inquiry.ts
> +            const inquiriesDataArray = Array.isArray(inquiriesData?.data)
Having issue while building to publish the package. So, it was my fix.

2023-02-17 05:08 UTC, Jscripter-pk commented on src/kross-client/inquiry.ts
> +            const inquiriesDataArray = Array.isArray(inquiriesData?.data)
please try a better and related one

2023-02-17 07:12 UTC, Jscripter-pk reviewed
@aziyatali I leave a comment check and test with that and then merge if working fine from data perspective

2023-02-17 07:12 UTC, Jscripter-pk commented on src/kross-client/inquiry.ts
> +            const inquiriesDataArray = Object.values(inquiriesData?.data);
test with this
const inquiriesDataArray : {[key: string] : any}[] = inquiriesData?.data ? ..........

2023-02-17 07:20 UTC, merged